# Generated by Django 2.2 on 2019-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='Hello-World'),
            preserve_default=False,
        ),
    ]
